### PR TITLE
Syntax changes

### PR DESCRIPTION
**Pull request by JasonMorgan**
Heyo, read your blog, enjoyed the article and figured I'd send a PR.

I've done the following:
- Added vscode files
- Modified the spacing to better support vscode
- changed your results check to use a switch
- removed the begin and process blocks

Might add some tests, right now I'm not confident that the updated results check block works as designed.  I'd also like to move that checker into it's own helper function.

### CODE REVIEW

**Comment by JasonMorgan** [comment]
There's a bit more than that but you can just review the commit log.

**Comment by JasonMorgan** [comment]
@drewfurgiuele holler at me if you have any questions.

**Comment by drewfurgiuele** [comment]
Thanks Jason! Let me test this out locally and then I'll approve the merge. Wondering if I should merge thsi to "master" or set up a "dev" branch to test changes in before merging to branch. Thoughts?

**Comment by JasonMorgan** [comment]
I don't think that's a good idea right now.  Lets write tests and go from there.  In general I think the whole branch/ merge to master thing is important but relies on good tests and some sort of CI/CD pipeline.  Also wouldn't want to keep a permanent dev branch.

**Comment by JasonMorgan** [comment]
Hey @drewfurgiuele need anything from me to move this forward?

**Comment by drewfurgiuele** [comment]
Oops, sorry, for some reason I wasn't getting notifications that people were submitting. I will commit the PR now.

**Pull request merged**
